### ISSUE TITLE
add 'mailto' in mail in footer list

### ISSUE THREAD

**Issue by Fabianko** [JSConfCL/org-landing#2]
en [file](https://github.com/JSConfCL/org-landing/blob/main/src/utils/data.js) linea 32 
` { id: 2, name: 'CONTACTO@JSCHILE.ORG', url: 'contacto@jschile.org'},` por ` { id: 2, name: 'CONTACTO@JSCHILE.ORG', url: 'mailto:contacto@jschile.org'},`

**Comment by joseglego** [comment]
Muchas gracias por el feedback! <3 

Esto ya debería estar en Producción. Ya hemos hecho merge del fix
